# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema-nomina-database
    username: ydvowbeeak
    password: qCIMXlnw9KAe$Q5t
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yoiberbeitar1@gmail.com
    password: acfl onqe shmt jxvr
    properties:
      mail:
        smtp:
          protocol: smtp
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
    protocol: smtp
secret:
  key: "solapa123ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789"
